# Generated by Django 4.2.4 on 2023-08-10 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField(verbose_name='Vencimento')),
                ('pay_day', models.DateField(verbose_name='Data de pagamento')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('expense', models.FloatField(verbose_name='Despesa')),
                ('status', models.CharField(choices=[(1, 'Pago'), (2, 'À pagar')], max_length=255, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Despesa',
                'verbose_name_plural': 'Despesas',
            },
        ),
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_revenue', models.DateField(verbose_name='Data da entrada')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição')),
                ('revenue', models.FloatField(verbose_name='Receita')),
            ],
            options={
                'verbose_name': 'Receita',
                'verbose_name_plural': 'Receitas',
            },
        ),
    ]
