# Generated by Django 4.2.4 on 2023-08-10 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_finance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='pay_day',
            field=models.DateField(blank=True, null=True, verbose_name='Data de pagamento'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='status',
            field=models.CharField(choices=[('PG', 'Pago'), ('APG', 'À pagar')], max_length=3, verbose_name='Status'),
        ),
    ]
